"""Regenerate SmaaHlsl.h from SMAA.hlsl.

MarniDX.cpp compiles the SMAA shaders at run time with D3DCompile, so the
shader source is built into the game as a byte array (an MSVC string literal
is limited to 64 KB, and SMAA.hlsl is close to that). Run this after
replacing SMAA.hlsl:

    python src/marni/smaa/gen_smaa_hlsl.py
"""
import os

here = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(here, "SMAA.hlsl"), "rb") as f:
    data = f.read()

lines = [
    "// Generated by gen_smaa_hlsl.py from SMAA.hlsl - do not edit.\n",
    "// SMAA (c) 2013 Jorge Jimenez et al., MIT license: see LICENSE.txt.\n",
    "#pragma once\n",
    "static const char g_SmaaHlsl[] = {\n",
]
for i in range(0, len(data), 24):
    lines.append("    " + "".join("0x%02x," % b for b in data[i:i + 24]) + "\n")
lines.append("    0x00\n};\n")
with open(os.path.join(here, "SmaaHlsl.h"), "w", newline="\n") as f:
    f.writelines(lines)
print("SmaaHlsl.h: %d bytes of shader source" % len(data))
